name: unit tests
on:
  push:
    branches:
      - trunk
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5, 6]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install modules
        run: yarn install
      - name: Run tests
        run: yarn test --shard=${{ matrix.shard }}/${{ strategy.job-total }} --passWithNoTests
      - name: Combine coverage
        run: yarn collectCoverage && mv coverage.info coverage${{matrix.shard}}.info
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage${{matrix.shard}}.info
